collections:
  - community.crypto
roles:
  - rockandska.erlang
  - geerlingguy.rabbitmq
  - src: git+https://opendev.org/openstack/openstack-ansible-apt_package_pinning
    name: apt_package_pinning
  - src: git+https://opendev.org/openstack/openstack-ansible-os_keystone
    name: os_keystone
    version: 91c397dc8b
  - src: git+https://opendev.org/openstack/ansible-role-python_venv_build
    name: python_venv_build
  - src: git+https://opendev.org/openstack/ansible-config_template
    name: config_template
  - src: git+https://opendev.org/openstack/ansible-role-systemd_service
    name: systemd_service
    version: fc698fb11a
