- name: "Setup VM with multipass"
  hosts: host
  vars:
    multipass_vm_username: "{{ vm_username }}"
    multipass_build_dir: "{{ build_dir }}"
    multipass_vm_name: "{{ vm_name }}"
    multipass_vm_release: "{{ vm_release }}"
  roles:
    - multipass_vm
  tasks:
    - name: "Set guest address"
      add_host:
        name: guest
        groups:
          - keystone_all
        ansible_host: "{{ multipass_vm_address }}"
        ansible_user: "{{ multipass_vm_username }}"
        ansible_ssh_private_key_file: "{{ vm_private_key_file }}"
        vm_address: "{{ multipass_vm_address }}"
      changed_when: no
