---
- name: "Prepare common configuration"
  hosts: host
  tasks:
    - name: Create keypair dir
      file:
        path: "{{ build_dir }}"
        state: directory
    - name: Generate keypair
      vars:
        keypair_type: ed25519
      community.crypto.openssh_keypair:
        path: "{{ build_dir }}/id_{{ keypair_type }}"
        type: "{{ keypair_type }}"
      register: keypair_result
    - name: Save keys to host vars
      set_fact:
        vm_public_key: "{{ keypair_result.public_key }}"
        vm_private_key_file: "{{ playbook_dir }}/{{ keypair_result.filename }}"

- import_playbook: create-multipass.yaml
  when: provider == "multipass"

- name: "Wait for ssh to be available"
  hosts: guest
  gather_facts: no
  tasks:
    - name: Wait for SSH available
      wait_for_connection:
        timeout: 60

- name: "Generate passwords"
  hosts: guest
  tasks:
    - set_fact:
        db_pwd: "{{ lookup('password', 'build/db_pwd chars=hexdigits', seed=inventory_hostname) }}"
        admin_pwd: "{{ lookup('password', 'build/admin_pwd', seed=inventory_hostname) }}"
      no_log: true

- name: "Prepare to install"
  hosts: guest
  become: yes
  tasks:
    - name: "Uninstall unused packages"
      apt:
        pkg:
          - cloud-init
          - python3-yaml
        state: absent
        force: yes
        purge: yes
        autoremove: yes
    - name: "Install packages"
      apt:
        pkg:
          - python3-pip
          - mysql-server
        state: latest
        autoremove: yes
        update_cache: yes
        cache_valid_time: 1200
    - name: "Upgrade PIP"
      pip:
        name:
          - pip
        state: latest
    - name: "Install PIP packages"
      pip:
        name:
          - openstacksdk
          - virtualenv
          - pymysql
        state: latest
    - name: "Create cgi-bin"
      file:
        path: "/var/www/cgi-bin/keystone"
        state: directory
    - name: "Create /etc/keystone"
      file:
        path: "/etc/keystone"
        state: directory
    - name: "Prepare keystone key pair"
      community.crypto.openssh_keypair:
        path: "/home/{{ vm_username }}/.ssh/id_rsa"
        type: "rsa"
    - name: "Create .my.cnf"
      copy:
        src: .my.cnf
        dest: "{{ item }}/.my.cnf"
      loop:
        - "/root"
        - "/home/{{ vm_username }}"
    - name: "Create openstack config dir"
      file:
        path: "~/.config/openstack/"
        state: directory
    - name: "Create clouds.yaml for post-install configuration"
      template:
        src: "clouds.yaml"
        dest: "~/.config/openstack/clouds.yaml"

- name: "Install RabbitMQ"
  hosts: guest
  become: yes
  vars:
    erlang_series: 24
    rabbitmq_version: 3.9.11
  roles:
    - rockandska.erlang
    - geerlingguy.rabbitmq

- name: "Ubuntu install"
  hosts: guest
  become: yes
  vars:
    internal_lb_vip_address: "{{ vm_address }}"
    external_lb_vip_address: "{{ vm_address }}"
    keystone_memcached_servers: ""
    keystone_container_mysql_password: "{{ db_pwd }}"
    keystone_oslomsg_rpc_password: "{{ db_pwd }}"
    keystone_system_user_home: "/home/keystone"
    keystone_db_setup_host: guest
    keystone_oslomsg_rpc_setup_host: guest
    keystone_oslomsg_notify_setup_host: guest
    keystone_service_setup_host: guest
    oslomsg_rpc_policies: [ ]
    keystone_admin_user_name: admin
    keystone_auth_admin_password: "{{ admin_pwd }}"
    login_project_name: "admin"
    login_user_domain_name: "Default"
  roles:
    - openstack.config_template
    - os_keystone
